using System;
using System.IO;

namespace WinBooster.Fixer.Fixes
{
    public class X7_Oscar_Keyboard_Editor : FixerI
    {
        #region Дефолтные файлы
        private string amc_data = 
            "<Root>\n" +
            "\t<DefaultMacro>\n" +
            "\t\t<Major></Major>\n" +
            "\t\t<Description></Description>\n" +
            "\t\t<Comment></Comment>\n" +
            "\t\t<GUIOption>\n" +
            "\t\t\t<RepeatType>0</RepeatType>\n" +
            "\t\t</GUIOption>\n" +
            "\t\t<KeyUp>\n" +
            "\t\t  <Syntax></Syntax>\n" +
            "\t\t</KeyUp>\n" +
            "\t\t<KeyDown>\n" +
            "\t\t  <Syntax>\n" +
            "//   новый скрипт ниже.\n" +
            "//-------------------\n" +
            "//3 метода создания скрипта\n" +
            "//1, включить функции из верхней левой панели\n" +
            "//2, запись движений мыши и клавиатуры\n" +
            "//3, веведите с клавиатуры\n" +
            ".</Syntax>\n" +
            "\t\t</KeyDown>\t\n" +
            "\t</DefaultMacro>\n" +
            "</Root>\n";
        private string asc_data = "<Root>\n" +
            "\t<DefaultScript>\n" +
            "\t\t<Major></Major>\n" +
            "\t\t<Description></Description>\n" +
            "\t\t<Comment></Comment>\n" +
            "\t\t\n" +
            "\t\t//Mode 0\n" +
            "\t\t<Trigger001>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>257</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger001>\n" +
            "\t\t<Trigger002>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>259</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger002>\n" +
            "\t\t<Trigger003>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>258</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger003>\n" +
            "\t\t<Trigger004>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>260</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger004>\n" +
            "\t\t<Trigger005>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>261</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger005>\n" +
            "\t\t<Trigger006>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>294</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger006>\n" +
            "\t\t<Trigger007>\n" +
            "\t\t\t<TriggerType>1</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName>Treble-Click</MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger007>\n" +
            "\t\t<Trigger008>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>307</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment>125Hz</Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger008>\n" +
            "\t\t<Trigger009>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>296</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger009>\n" +
            "\t\t<Trigger010>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>297</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger010>\n" +
            "\t\t<Trigger011>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger011>\n" +
            "\t\t<Trigger012>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger012>\n" +
            "\t\t<Trigger013>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger013>\n" +
            "\t\t<Trigger014>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger014>\n" +
            "\t\t<Trigger015>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger015>\n" +
            "\t\t<Trigger016>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger016>\n" +
            "\t\t<Trigger041>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger041>\n" +
            "\t\t<Trigger042>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger042>\n" +
            "                <Trigger043>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger043>\n" +
            "\t\t<Trigger044>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger044>\n" +
            "\t\t<Trigger045>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger045>\n" +
            "\t\t<Trigger046>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger046>\n" +
            "\t\t//Mode 1\n" +
            "\t\t<Trigger101>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>257</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger101>\n" +
            "\t\t<Trigger102>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>259</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger102>\n" +
            "\t\t<Trigger103>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>258</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger103>\n" +
            "\t\t<Trigger104>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>260</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger104>\n" +
            "\t\t<Trigger105>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>261</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger105>\n" +
            "\t\t<Trigger106>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>294</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger106>\n" +
            "\t\t<Trigger107>\n" +
            "\t\t\t<TriggerType>1</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName>Treble-Click</MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger107>\n" +
            "\t\t<Trigger108>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>307</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment>125Hz</Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger108>\n" +
            "\t\t<Trigger109>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>296</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger109>\n" +
            "\t\t<Trigger110>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>297</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger110>\n" +
            "\t\t<Trigger111>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger111>\n" +
            "\t\t<Trigger112>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger112>\n" +
            "\t\t<Trigger113>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger113>\n" +
            "\t\t<Trigger114>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger114>\n" +
            "\t\t<Trigger115>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger115>\n" +
            "\t\t<Trigger116>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger116>\n" +
            "\t\t<Trigger141>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger141>\n" +
            "\t\t<Trigger142>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger142>\n" +
            "\t\t<Trigger143>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger143>\n" +
            "\t\t<Trigger144>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger144>\n" +
            "\t\t<Trigger145>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger145>\n" +
            "\t\t<Trigger146>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger146>\n" +
            "\t\t//Mode 2\n" +
            "\t\t<Trigger201>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>257</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger201>\n" +
            "\t\t<Trigger202>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>259</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger202>\n" +
            "\t\t<Trigger203>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>258</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger203>\n" +
            "\t\t<Trigger204>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>260</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger204>\n" +
            "\t\t<Trigger205>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>261</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger205>\n" +
            "\t\t<Trigger206>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>294</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger206>\n" +
            "\t\t<Trigger207>\n" +
            "\t\t\t<TriggerType>1</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName>Treble-Click</MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger207>\n" +
            "\t\t<Trigger208>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>307</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment>125Hz</Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger208>\n" +
            "\t\t<Trigger209>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>296</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger209>\n" +
            "\t\t<Trigger210>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>297</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger210>\n" +
            "\t\t<Trigger211>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger211>\n" +
            "\t\t<Trigger212>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger212>\n" +
            "\t\t<Trigger213>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger213>\n" +
            "\t\t<Trigger214>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger214>\n" +
            "\t\t<Trigger215>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger215>\n" +
            "\t\t<Trigger216>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger216>\n" +
            "\t\t<Trigger241>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger241>\n" +
            "\t\t<Trigger242>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger242>\n" +
            "\t\t<Trigger243>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger243>\n" +
            "\t\t<Trigger244>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger244>\n" +
            "\t\t<Trigger245>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger245>\n" +
            "\t\t<Trigger246>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger246>\t\t\n" +
            "\t\t//Mode 3\n" +
            "\t\t<Trigger301>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>257</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger301>\n" +
            "\t\t<Trigger302>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>259</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger302>\n" +
            "\t\t<Trigger303>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>258</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger303>\n" +
            "\t\t<Trigger304>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>260</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger304>\n" +
            "\t\t<Trigger305>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>261</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger305>\n" +
            "\t\t<Trigger306>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>294</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger306>\n" +
            "\t\t<Trigger307>\n" +
            "\t\t\t<TriggerType>1</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName>Treble-Click</MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger307>\n" +
            "\t\t<Trigger308>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>307</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment>125Hz</Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger308>\n" +
            "\t\t<Trigger309>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>296</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger309>\n" +
            "\t\t<Trigger310>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>297</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger310>\n" +
            "\t\t<Trigger311>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger311>\n" +
            "\t\t<Trigger312>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger312>\n" +
            "\t\t<Trigger313>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger313>\n" +
            "\t\t<Trigger314>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger314>\n" +
            "\t\t<Trigger315>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger315>\n" +
            "\t\t<Trigger316>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger316>\n" +
            "\t\t<Trigger341>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger341>\n" +
            "\t\t<Trigger342>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger342>\n" +
            "\t\t<Trigger343>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger343>\n" +
            "\t\t<Trigger344>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger344>\n" +
            "\t\t<Trigger345>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger345>\n" +
            "\t\t<Trigger346>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger346>\n" +
            "\t\t//Mode 4\n" +
            "\t\t<Trigger401>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>257</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger401>\n" +
            "\t\t<Trigger402>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>259</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger402>\n" +
            "\t\t<Trigger403>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>258</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger403>\n" +
            "\t\t<Trigger404>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>260</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger404>\n" +
            "\t\t<Trigger405>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>261</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger405>\n" +
            "\t\t<Trigger406>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>294</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger406>\n" +
            "\t\t<Trigger407>\n" +
            "\t\t\t<TriggerType>1</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName>Treble-Click</MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger407>\n" +
            "\t\t<Trigger408>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>307</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment>125Hz</Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger408>\n" +
            "\t\t<Trigger409>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>296</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger409>\n" +
            "\t\t<Trigger410>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>297</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger410>\n" +
            "\t\t<Trigger411>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger411>\n" +
            "\t\t<Trigger412>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger412>\n" +
            "\t\t<Trigger413>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger413>\n" +
            "\t\t<Trigger414>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger414>\n" +
            "\t\t<Trigger415>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger415>\n" +
            "\t\t<Trigger416>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>256</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger416>\n" +
            "\t\t<Trigger441>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger441>\n" +
            "\t\t<Trigger442>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger442>\n" +
            "\t\t<Trigger443>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger443>\n" +
            "\t\t<Trigger444>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger444>\n" +
            "\t\t<Trigger445>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>262</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger445>\n" +
            "\t\t<Trigger446>\n" +
            "\t\t\t<TriggerType>0</TriggerType>\n" +
            "\t\t\t<EventCode>263</EventCode>\n" +
            "\t\t\t<MacroPath></MacroPath>\n" +
            "\t\t\t<MacroName></MacroName>\n" +
            "\t\t\t<Text></Text>\n" +
            "\t\t\t<Comment></Comment>\n" +
            "\t\t\t<Append></Append>\n" +
            "\t\t\t<Reserve1></Reserve1>\n" +
            "\t\t\t<Reserve2></Reserve2>\n" +
            "\t\t</Trigger446>\t\t\n" +
            "\t\t\n" +
            "\t\t\n" +
            "\t\t\t\t\n" +
            "\t\t//DPI\n" +
            "\t\t<DPI>\n" +
            "\t\t\t<Valid>0</Valid>\n" +
            "\t\t\t<DPI0>\n" +
            "\t\t\t\t<AxisX>600</AxisX>\n" +
            "\t\t\t\t<AxisY>600</AxisY>\n" +
            "\t\t\t\t<Enable>1</Enable>\n" +
            "\t\t\t\t<LED>0</LED>\n" +
            "\t\t\t</DPI0>\n" +
            "\t\t\t<DPI1>\n" +
            "\t\t\t\t<AxisX>800</AxisX>\n" +
            "\t\t\t\t<AxisY>800</AxisY>\n" +
            "\t\t\t\t<Enable>1</Enable>\n" +
            "\t\t\t\t<LED>1</LED>\n" +
            "\t\t\t</DPI1>\n" +
            "\t\t\t<DPI2>\n" +
            "\t\t\t\t<AxisX>1200</AxisX>\n" +
            "\t\t\t\t<AxisY>1200</AxisY>\n" +
            "\t\t\t\t<Enable>1</Enable>\n" +
            "\t\t\t\t<LED>2</LED>\n" +
            "\t\t\t</DPI2>\n" +
            "\t\t\t<DPI3>\n" +
            "\t\t\t\t<AxisX>1600</AxisX>\n" +
            "\t\t\t\t<AxisY>1600</AxisY>\n" +
            "\t\t\t\t<Enable>1</Enable>\n" +
            "\t\t\t\t<LED>3</LED>\n" +
            "\t\t\t</DPI3>\n" +
            "\t\t\t<DPI4>\n" +
            "\t\t\t\t<AxisX>2000</AxisX>\n" +
            "\t\t\t\t<AxisY>2000</AxisY>\n" +
            "\t\t\t\t<Enable>1</Enable>\n" +
            "\t\t\t\t<LED>4</LED>\n" +
            "\t\t\t</DPI4>\n" +
            "\t\t\t<DPI5>\n" +
            "\t\t\t\t<AxisX>2500</AxisX>\n" +
            "\t\t\t\t<AxisY>2500</AxisY>\n" +
            "\t\t\t\t<Enable>1</Enable>\n" +
            "\t\t\t\t<LED>5</LED>\n" +
            "\t\t\t</DPI5>\n" +
            "\t\t</DPI>\n" +
            "\t</DefaultScript>\n" +
            "</Root>\n";
        #endregion

        private readonly string config_dir = Utils.GetSysDrive() + "\\Program Files (x86)\\X7 Oscar Keyboard Editor\\Data\\X7_Keyboard\\Forms\\MacroEdit\\Text";
        private readonly string standartFile_dir = Utils.GetSysDrive() + "\\Program Files (x86)\\X7 Oscar Keyboard Editor\\ScriptsMacros\\Russian\\StandardFile";
        public void Fix()
        {
            if (Directory.Exists(config_dir) && Directory.Exists(standartFile_dir))
            {
                if (!File.Exists(standartFile_dir + "\\" + NullScript + ".ASC"))
                {
                    File.Create(standartFile_dir + "\\" + NullScript + ".ASC").Close();
                    File.WriteAllText(standartFile_dir + "\\" + NullScript + ".ASC", asc_data);
                }
                if (!File.Exists(standartFile_dir + "\\" + NullMacro + ".amc"))
                {
                    File.Create(standartFile_dir + "\\" + NullMacro + ".amc").Close();
                    File.WriteAllText(standartFile_dir + "\\" + NullMacro + ".amc", amc_data);
                }
            }
        }
        private string NullScript = "";
        private string NullMacro = "";
        public bool NeedFix()
        {
            if (Directory.Exists(config_dir))
            {
                if (File.Exists(config_dir + "\\Russian.txt"))
                {
                    string[] lines = File.ReadAllLines(config_dir + "\\Russian.txt");
                    foreach (string line in lines)
                    {
                        string[] key_value = line.Split('=');
                        if (key_value.Length == 2)
                        {
                            if (key_value[0] == "NullScript")
                            {
                                NullScript = key_value[1];
                            }
                            else if (key_value[0] == "NullMacro")
                            {
                                NullMacro = key_value[1];
                            }
                        }
                    }
                }
            }
            if (Directory.Exists(config_dir) && Directory.Exists(standartFile_dir))
            {
                if (!File.Exists(standartFile_dir + "\\" + NullScript + ".ASC"))
                {
                    return true;
                }
                if (!File.Exists(standartFile_dir + "\\" + NullMacro + ".amc"))
                {
                    return true;
                }
            }
            return false;
        }
    }
}
